#!/bin/bash

## FLUSH CHAINS
#  ------------

iptables -F
iptables -X
iptables -Z
iptables -t nat --flush



#################################################################################################################################
#################################################################################################################################
#
#		VARIABLES
#
#################################################################################################################################
#################################################################################################################################

### INTERFACES
# ------------
WAN1="eth0"
LAN="eth1"
SER="eth2"
NET_ALL="$LAN,$SER"

### PORTS
# -------
PG_DEFWEB=80,443
SSH=22



#################################################################################################################################
#################################################################################################################################
#
#		FIREWALL
#		INPUT - OUTPUT
#
#################################################################################################################################
#################################################################################################################################

### ESTABLISHED and RELATED
# -------------------------
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

### LOOPBACK
# ----------
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

# -------------------------
### GENERAL INPUT - OUTPUT
# -------------------------

### ALLOW SSH TO FIREWALL (Need IPset)
#iptables -A INPUT -m set --match-set ZA src -m multiport -p tcp --dport $SSH -m state --state NEW,ESTABLISHED -j ACCEPT

### ALLOW SSH TO FIREWALL
iptables -A INPUT -s 102.0.0.0/8 -m multiport -p tcp --dport $SSH -m state --state NEW,ESTABLISHED -j ACCEPT

### DNS
iptables -A OUTPUT -m multiport -p tcp --dport 53 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -m multiport -p udp --dport 53 -m state --state NEW,ESTABLISHED -j ACCEPT

### PING
iptables -A OUTPUT -p icmp -m state --state NEW,ESTABLISHED -j ACCEPT

### ALLOW FW WEB ACCESS
iptables -A OUTPUT -m multiport -p tcp --dport $PG_DEFWEB -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT



#################################################################################################################################
#################################################################################################################################
#
#		FORWARDING
#
#################################################################################################################################
#################################################################################################################################

### ESTABLISHED and RELATED
# -------------------------
iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT

### MASQUARADING
# --------------
iptables -t nat -A POSTROUTING -o $WAN1 -j MASQUERADE



# --------------------
### GENERAL FORWARDING
# --------------------

#allow 192.168.0.10 to all
iptables -A FORWARD -i $LAN -o $WAN1 -s 192.168.0.10 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT


#################################################################################################################################
#################################################################################################################################
#
#		DEFAULT RULE
#
#################################################################################################################################
#################################################################################################################################

## DEFAULT DROP POLICIES
#  ---------------------
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP